// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BackOffice.Web.Controllers
{
    public partial class InsuranceController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InsuranceController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected InsuranceController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InsuranceList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InsuranceList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InsuranceUpsert()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InsuranceUpsert);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public InsuranceController Actions { get { return MVC.Insurance; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Insurance";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Insurance";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string InsuranceList = "InsuranceList";
            public readonly string InsuranceUpsert = "InsuranceUpsert";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string InsuranceList = "InsuranceList";
            public const string InsuranceUpsert = "InsuranceUpsert";
        }


        static readonly ActionParamsClass_InsuranceList s_params_InsuranceList = new ActionParamsClass_InsuranceList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsuranceList InsuranceListParams { get { return s_params_InsuranceList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsuranceList
        {
            public readonly string param = "param";
        }
        static readonly ActionParamsClass_InsuranceUpsert s_params_InsuranceUpsert = new ActionParamsClass_InsuranceUpsert();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsuranceUpsert InsuranceUpsertParams { get { return s_params_InsuranceUpsert; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsuranceUpsert
        {
            public readonly string insuranceId = "insuranceId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_InsuranceController : BackOffice.Web.Controllers.InsuranceController
    {
        public T4MVC_InsuranceController() : base(Dummy.Instance) { }

        [NonAction]
        partial void InsuranceListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string param);

        [NonAction]
        public override System.Web.Mvc.ActionResult InsuranceList(string param)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InsuranceList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            InsuranceListOverride(callInfo, param);
            return callInfo;
        }

        [NonAction]
        partial void InsuranceUpsertOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string insuranceId);

        [NonAction]
        public override System.Web.Mvc.ActionResult InsuranceUpsert(string insuranceId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InsuranceUpsert);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "insuranceId", insuranceId);
            InsuranceUpsertOverride(callInfo, insuranceId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
