// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Web
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _L_Header = "_L_Header";
                public readonly string _L_PrincipalMenu = "_L_PrincipalMenu";
                public readonly string _Layout = "_Layout";
                public readonly string _P_ProfileInfo = "_P_ProfileInfo";
                public readonly string _P_ProfileMenu = "_P_ProfileMenu";
                public readonly string _P_ProfileOfficeMenu = "_P_ProfileOfficeMenu";
                public readonly string _PA_PatientInfo = "_PA_PatientInfo";
                public readonly string _PA_PatientMenu = "_PA_PatientMenu";
            }
            public readonly string _L_Header = "~/Areas/Web/Views/Shared/_L_Header.cshtml";
            public readonly string _L_PrincipalMenu = "~/Areas/Web/Views/Shared/_L_PrincipalMenu.cshtml";
            public readonly string _Layout = "~/Areas/Web/Views/Shared/_Layout.cshtml";
            public readonly string _P_ProfileInfo = "~/Areas/Web/Views/Shared/_P_ProfileInfo.cshtml";
            public readonly string _P_ProfileMenu = "~/Areas/Web/Views/Shared/_P_ProfileMenu.cshtml";
            public readonly string _P_ProfileOfficeMenu = "~/Areas/Web/Views/Shared/_P_ProfileOfficeMenu.cshtml";
            public readonly string _PA_PatientInfo = "~/Areas/Web/Views/Shared/_PA_PatientInfo.cshtml";
            public readonly string _PA_PatientMenu = "~/Areas/Web/Views/Shared/_PA_PatientMenu.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
