// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BackOffice.Web.Areas.Web.Controllers
{
    public partial class SpecialtyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SpecialtyController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SpecialtyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SpecialtyList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SpecialtyList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SpecialtyUpsert()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SpecialtyUpsert);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SpecialtyController Actions { get { return MVC.Web.Specialty; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Web";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Specialty";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Specialty";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string SpecialtyList = "SpecialtyList";
            public readonly string SpecialtyUpsert = "SpecialtyUpsert";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string SpecialtyList = "SpecialtyList";
            public const string SpecialtyUpsert = "SpecialtyUpsert";
        }


        static readonly ActionParamsClass_SpecialtyList s_params_SpecialtyList = new ActionParamsClass_SpecialtyList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SpecialtyList SpecialtyListParams { get { return s_params_SpecialtyList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SpecialtyList
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
        }
        static readonly ActionParamsClass_SpecialtyUpsert s_params_SpecialtyUpsert = new ActionParamsClass_SpecialtyUpsert();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SpecialtyUpsert SpecialtyUpsertParams { get { return s_params_SpecialtyUpsert; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SpecialtyUpsert
        {
            public readonly string SpecialtyPublicId = "SpecialtyPublicId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Search = "Search";
                public readonly string SpecialtyList = "SpecialtyList";
                public readonly string SpecialtyUpsert = "SpecialtyUpsert";
            }
            public readonly string Search = "~/Areas/Web/Views/Specialty/Search.cshtml";
            public readonly string SpecialtyList = "~/Areas/Web/Views/Specialty/SpecialtyList.cshtml";
            public readonly string SpecialtyUpsert = "~/Areas/Web/Views/Specialty/SpecialtyUpsert.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SpecialtyController : BackOffice.Web.Areas.Web.Controllers.SpecialtyController
    {
        public T4MVC_SpecialtyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void SpecialtyListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult SpecialtyList(string ProfilePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SpecialtyList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            SpecialtyListOverride(callInfo, ProfilePublicId);
            return callInfo;
        }

        [NonAction]
        partial void SpecialtyUpsertOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string SpecialtyPublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult SpecialtyUpsert(string SpecialtyPublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SpecialtyUpsert);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "SpecialtyPublicId", SpecialtyPublicId);
            SpecialtyUpsertOverride(callInfo, SpecialtyPublicId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
