// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BackOffice.Web.Areas.Web.Controllers
{
    public partial class ProfileController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ProfileController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProfileEdit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProfileEditImage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileEditImage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OfficeList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OfficeList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OfficeUpsert()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OfficeUpsert);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SpecialtyProfileList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SpecialtyProfileList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult InsuranceProfileList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InsuranceProfileList);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ProfileController Actions { get { return MVC.Web.Profile; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Web";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Profile";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Profile";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ProfileSearch = "ProfileSearch";
            public readonly string ProfileCreate = "ProfileCreate";
            public readonly string ProfileEdit = "ProfileEdit";
            public readonly string ProfileEditImage = "ProfileEditImage";
            public readonly string OfficeList = "OfficeList";
            public readonly string OfficeUpsert = "OfficeUpsert";
            public readonly string SpecialtyProfileList = "SpecialtyProfileList";
            public readonly string InsuranceProfileList = "InsuranceProfileList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ProfileSearch = "ProfileSearch";
            public const string ProfileCreate = "ProfileCreate";
            public const string ProfileEdit = "ProfileEdit";
            public const string ProfileEditImage = "ProfileEditImage";
            public const string OfficeList = "OfficeList";
            public const string OfficeUpsert = "OfficeUpsert";
            public const string SpecialtyProfileList = "SpecialtyProfileList";
            public const string InsuranceProfileList = "InsuranceProfileList";
        }


        static readonly ActionParamsClass_ProfileEdit s_params_ProfileEdit = new ActionParamsClass_ProfileEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProfileEdit ProfileEditParams { get { return s_params_ProfileEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProfileEdit
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
        }
        static readonly ActionParamsClass_ProfileEditImage s_params_ProfileEditImage = new ActionParamsClass_ProfileEditImage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProfileEditImage ProfileEditImageParams { get { return s_params_ProfileEditImage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProfileEditImage
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
        }
        static readonly ActionParamsClass_OfficeList s_params_OfficeList = new ActionParamsClass_OfficeList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OfficeList OfficeListParams { get { return s_params_OfficeList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OfficeList
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
        }
        static readonly ActionParamsClass_OfficeUpsert s_params_OfficeUpsert = new ActionParamsClass_OfficeUpsert();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OfficeUpsert OfficeUpsertParams { get { return s_params_OfficeUpsert; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OfficeUpsert
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
            public readonly string OfficePublicId = "OfficePublicId";
        }
        static readonly ActionParamsClass_SpecialtyProfileList s_params_SpecialtyProfileList = new ActionParamsClass_SpecialtyProfileList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SpecialtyProfileList SpecialtyProfileListParams { get { return s_params_SpecialtyProfileList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SpecialtyProfileList
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
        }
        static readonly ActionParamsClass_InsuranceProfileList s_params_InsuranceProfileList = new ActionParamsClass_InsuranceProfileList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_InsuranceProfileList InsuranceProfileListParams { get { return s_params_InsuranceProfileList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_InsuranceProfileList
        {
            public readonly string ProfilePublicId = "ProfilePublicId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string InsuranceProfileList = "InsuranceProfileList";
                public readonly string OfficeList = "OfficeList";
                public readonly string OfficeUpsert = "OfficeUpsert";
                public readonly string ProfileCreate = "ProfileCreate";
                public readonly string ProfileEdit = "ProfileEdit";
                public readonly string ProfileEditImage = "ProfileEditImage";
                public readonly string ProfileSearch = "ProfileSearch";
                public readonly string SpecialtyProfileList = "SpecialtyProfileList";
            }
            public readonly string InsuranceProfileList = "~/Areas/Web/Views/Profile/InsuranceProfileList.cshtml";
            public readonly string OfficeList = "~/Areas/Web/Views/Profile/OfficeList.cshtml";
            public readonly string OfficeUpsert = "~/Areas/Web/Views/Profile/OfficeUpsert.cshtml";
            public readonly string ProfileCreate = "~/Areas/Web/Views/Profile/ProfileCreate.cshtml";
            public readonly string ProfileEdit = "~/Areas/Web/Views/Profile/ProfileEdit.cshtml";
            public readonly string ProfileEditImage = "~/Areas/Web/Views/Profile/ProfileEditImage.cshtml";
            public readonly string ProfileSearch = "~/Areas/Web/Views/Profile/ProfileSearch.cshtml";
            public readonly string SpecialtyProfileList = "~/Areas/Web/Views/Profile/SpecialtyProfileList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ProfileController : BackOffice.Web.Areas.Web.Controllers.ProfileController
    {
        public T4MVC_ProfileController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ProfileSearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProfileSearch()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileSearch);
            ProfileSearchOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProfileCreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProfileCreate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileCreate);
            ProfileCreateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProfileEditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProfileEdit(string ProfilePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            ProfileEditOverride(callInfo, ProfilePublicId);
            return callInfo;
        }

        [NonAction]
        partial void ProfileEditImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProfileEditImage(string ProfilePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProfileEditImage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            ProfileEditImageOverride(callInfo, ProfilePublicId);
            return callInfo;
        }

        [NonAction]
        partial void OfficeListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult OfficeList(string ProfilePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OfficeList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            OfficeListOverride(callInfo, ProfilePublicId);
            return callInfo;
        }

        [NonAction]
        partial void OfficeUpsertOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId, string OfficePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult OfficeUpsert(string ProfilePublicId, string OfficePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OfficeUpsert);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "OfficePublicId", OfficePublicId);
            OfficeUpsertOverride(callInfo, ProfilePublicId, OfficePublicId);
            return callInfo;
        }

        [NonAction]
        partial void SpecialtyProfileListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult SpecialtyProfileList(string ProfilePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SpecialtyProfileList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            SpecialtyProfileListOverride(callInfo, ProfilePublicId);
            return callInfo;
        }

        [NonAction]
        partial void InsuranceProfileListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string ProfilePublicId);

        [NonAction]
        public override System.Web.Mvc.ActionResult InsuranceProfileList(string ProfilePublicId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.InsuranceProfileList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ProfilePublicId", ProfilePublicId);
            InsuranceProfileListOverride(callInfo, ProfilePublicId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
