//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Message.Inalambria.ServiceInalambria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="soa.inalambria.com", ConfigurationName="ServiceInalambria.ServiceSendSoap")]
    public interface ServiceSendSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/Send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Message.Inalambria.ServiceInalambria.Transaction Send(string TicketTGS, string DeviceNumber, string Message, string DateMessage, string Provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/Send", ReplyAction="*")]
        System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> SendAsync(string TicketTGS, string DeviceNumber, string Message, string DateMessage, string Provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/SendWithHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Message.Inalambria.ServiceInalambria.Transaction SendWithHash(string Hash, string User, string DeviceNumber, string Message, string DateMessage, string Provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/SendWithHash", ReplyAction="*")]
        System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> SendWithHashAsync(string Hash, string User, string DeviceNumber, string Message, string DateMessage, string Provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/SendWithUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Message.Inalambria.ServiceInalambria.Transaction SendWithUser(string User, string Password, string DeviceNumber, string Message, string DateMessage, string Provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/SendWithUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> SendWithUserAsync(string User, string Password, string DeviceNumber, string Message, string DateMessage, string Provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/CancelTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Message.Inalambria.ServiceInalambria.Transaction CancelTicket(string TicketTGS, string TicketSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/CancelTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> CancelTicketAsync(string TicketTGS, string TicketSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/CancelTicketWithHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Message.Inalambria.ServiceInalambria.Transaction CancelTicketWithHash(string Hash, string User, string TicketSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/CancelTicketWithHash", ReplyAction="*")]
        System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> CancelTicketWithHashAsync(string Hash, string User, string TicketSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/CancelTicketWithUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Message.Inalambria.ServiceInalambria.Transaction CancelTicketWithUser(string User, string Password, string TicketSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="soa.inalambria.com/CancelTicketWithUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> CancelTicketWithUserAsync(string User, string Password, string TicketSMS);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="soa.inalambria.com")]
    public partial class Transaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool statusField;
        
        private string ticketKdcField;
        
        private string ticketTransactionField;
        
        private string detailField;
        
        private System.DateTime dateArrivedField;
        
        private System.DateTime dateSendField;
        
        private ResponseValidation validationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TicketKdc {
            get {
                return this.ticketKdcField;
            }
            set {
                this.ticketKdcField = value;
                this.RaisePropertyChanged("TicketKdc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TicketTransaction {
            get {
                return this.ticketTransactionField;
            }
            set {
                this.ticketTransactionField = value;
                this.RaisePropertyChanged("TicketTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateArrived {
            get {
                return this.dateArrivedField;
            }
            set {
                this.dateArrivedField = value;
                this.RaisePropertyChanged("DateArrived");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime DateSend {
            get {
                return this.dateSendField;
            }
            set {
                this.dateSendField = value;
                this.RaisePropertyChanged("DateSend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ResponseValidation Validation {
            get {
                return this.validationField;
            }
            set {
                this.validationField = value;
                this.RaisePropertyChanged("Validation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="soa.inalambria.com")]
    public partial class ResponseValidation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ValidationPhoneResult[] mobileField;
        
        private string[] messageField;
        
        private int partField;
        
        private string errorMessageField;
        
        private int numErrorField;
        
        private bool stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ValidationPhoneResult[] Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
                this.RaisePropertyChanged("Part");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int NumError {
            get {
                return this.numErrorField;
            }
            set {
                this.numErrorField = value;
                this.RaisePropertyChanged("NumError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="soa.inalambria.com")]
    public partial class ValidationPhoneResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string phoneField;
        
        private double operatorField;
        
        private int codeBillingField;
        
        private string messageBillingField;
        
        private string codeMessageField;
        
        private int partField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CodeBilling {
            get {
                return this.codeBillingField;
            }
            set {
                this.codeBillingField = value;
                this.RaisePropertyChanged("CodeBilling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MessageBilling {
            get {
                return this.messageBillingField;
            }
            set {
                this.messageBillingField = value;
                this.RaisePropertyChanged("MessageBilling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodeMessage {
            get {
                return this.codeMessageField;
            }
            set {
                this.codeMessageField = value;
                this.RaisePropertyChanged("CodeMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
                this.RaisePropertyChanged("Part");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSendSoapChannel : Message.Inalambria.ServiceInalambria.ServiceSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSendSoapClient : System.ServiceModel.ClientBase<Message.Inalambria.ServiceInalambria.ServiceSendSoap>, Message.Inalambria.ServiceInalambria.ServiceSendSoap {
        
        public ServiceSendSoapClient() {
        }
        
        public ServiceSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Message.Inalambria.ServiceInalambria.Transaction Send(string TicketTGS, string DeviceNumber, string Message, string DateMessage, string Provider) {
            return base.Channel.Send(TicketTGS, DeviceNumber, Message, DateMessage, Provider);
        }
        
        public System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> SendAsync(string TicketTGS, string DeviceNumber, string Message, string DateMessage, string Provider) {
            return base.Channel.SendAsync(TicketTGS, DeviceNumber, Message, DateMessage, Provider);
        }
        
        public Message.Inalambria.ServiceInalambria.Transaction SendWithHash(string Hash, string User, string DeviceNumber, string Message, string DateMessage, string Provider) {
            return base.Channel.SendWithHash(Hash, User, DeviceNumber, Message, DateMessage, Provider);
        }
        
        public System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> SendWithHashAsync(string Hash, string User, string DeviceNumber, string Message, string DateMessage, string Provider) {
            return base.Channel.SendWithHashAsync(Hash, User, DeviceNumber, Message, DateMessage, Provider);
        }
        
        public Message.Inalambria.ServiceInalambria.Transaction SendWithUser(string User, string Password, string DeviceNumber, string Message, string DateMessage, string Provider) {
            return base.Channel.SendWithUser(User, Password, DeviceNumber, Message, DateMessage, Provider);
        }
        
        public System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> SendWithUserAsync(string User, string Password, string DeviceNumber, string Message, string DateMessage, string Provider) {
            return base.Channel.SendWithUserAsync(User, Password, DeviceNumber, Message, DateMessage, Provider);
        }
        
        public Message.Inalambria.ServiceInalambria.Transaction CancelTicket(string TicketTGS, string TicketSMS) {
            return base.Channel.CancelTicket(TicketTGS, TicketSMS);
        }
        
        public System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> CancelTicketAsync(string TicketTGS, string TicketSMS) {
            return base.Channel.CancelTicketAsync(TicketTGS, TicketSMS);
        }
        
        public Message.Inalambria.ServiceInalambria.Transaction CancelTicketWithHash(string Hash, string User, string TicketSMS) {
            return base.Channel.CancelTicketWithHash(Hash, User, TicketSMS);
        }
        
        public System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> CancelTicketWithHashAsync(string Hash, string User, string TicketSMS) {
            return base.Channel.CancelTicketWithHashAsync(Hash, User, TicketSMS);
        }
        
        public Message.Inalambria.ServiceInalambria.Transaction CancelTicketWithUser(string User, string Password, string TicketSMS) {
            return base.Channel.CancelTicketWithUser(User, Password, TicketSMS);
        }
        
        public System.Threading.Tasks.Task<Message.Inalambria.ServiceInalambria.Transaction> CancelTicketWithUserAsync(string User, string Password, string TicketSMS) {
            return base.Channel.CancelTicketWithUserAsync(User, Password, TicketSMS);
        }
    }
}
